name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webfood-nest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: webfood-nest/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Run e2e tests
        run: npm run test:e2e
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webfood-nest
    concurrency: heroku-deploy
    needs: backend
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: webfood-nest
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: webfood-fullstack
          heroku_email: danielcsullog@gmail.com
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webfood-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache-dependency-path: webfood-client/package-lock.json
      - name: Install dependencies
        run: npm i
     # - name: Run tests
     #   run: npm run test:ci
  frontend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webfood-client
    concurrency: heroku-deploy
    needs: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: webfood-client
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: webfood-fullstack-client
          heroku_email: danielcsullog@gmail.com
